artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_url: https://github.com/amitgurkhe/ML-Classification/raw/main/bank-additional-full.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir : artifacts/data_ingestion